### ISSUE TITLE
Plugin Issue on Jenkins

### ISSUE THREAD

**Issue by milindbangar79** [anchore/anchore#45]
Hi,

I am evaluating the plugin to be using as part of CI pipeline on Jenkins.

However the Anchore analysis's failing with the following error:

$ docker exec jenkins_anchore anchore analyze --skipgates --imagefile /root/anchore.TestAnchoreAnalysis_6/images
**Error setting up/reading Anchore configuration
Info: [Errno 13] Permission denied: '/root/.anchore/conf'**
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore/cli/__init__.py", line 150, in main_entry
    anchore_conf = AnchoreConfiguration(cliargs=args)
  File "/usr/lib/python2.7/site-packages/anchore/configuration.py", line 83, in __init__
    self.config_dir, self.config_file = self.find_config_file()
  File "/usr/lib/python2.7/site-packages/anchore/configuration.py", line 172, in find_config_file
    os.makedirs(self.DEFAULT_CONFIG_DIR)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/root/.anchore/conf'
Expected, but did not find configuration file at /root/.anchore/conf/config.yaml
2017-11-01T14:13:42.024 ERROR  AnchoreWorker   Anchore analyzer failed with return code 1, check output above for details
2017-11-01T14:13:42.024 ERROR  AnchorePlugin   Failing Anchore Container Image Scanner Plugin build step due to errors in plugin execution
hudson.AbortException: Anchore analyzer failed, check output above for details
	at com.anchore.jenkins.plugins.anchore.BuildWorker.runAnalyzerLocal(BuildWorker.java:295)
	at com.anchore.jenkins.plugins.anchore.BuildWorker.runAnalyzer(BuildWorker.java:175)
	at com.anchore.jenkins.plugins.anchore.AnchoreBuilder.perform(AnchoreBuilder.java:233)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
$ docker exec jenkins_anchore rm -rf /root/anchore.TestAnchoreAnalysis_6
$ docker exec jenkins_anchore anchore toolbox --image experiencedevops/customerservice:6-d27f03d delete --dontask
Error setting up/reading Anchore configuration
Info: [Errno 13] Permission denied: '/root/.anchore/conf'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore/cli/__init__.py", line 150, in main_entry
    anchore_conf = AnchoreConfiguration(cliargs=args)
  File "/usr/lib/python2.7/site-packages/anchore/configuration.py", line 83, in __init__
    self.config_dir, self.config_file = self.find_config_file()
  File "/usr/lib/python2.7/site-packages/anchore/configuration.py", line 172, in find_config_file
    os.makedirs(self.DEFAULT_CONFIG_DIR)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/root/.anchore/conf'
Expected, but did not find configuration file at /root/.anchore/conf/config.yaml
2017-11-01T14:13:42.527 WARN   AnchoreWorker   Failed to delete analytics for experiencedevops/customerservice:6-d27f03d from Anchore database, process returned 1

Can you please help.

Followed the config as provided in the project.

Thanks in advance

Milind

**Comment by nurmi** [comment]
Hi Milind,

The error looks like the permissions that are set on your anchore volume are not allowing the system to write - I'm assuming that you have set your "Local Anchore Data Volume" to some location (please correct this assumption if this is incorrect), and if so then the solution is to ensure that this location exists on your jenkins worker host and has permissions set to allow write access.  For example, on the jenkins worker in question, the following procedure should both help determine the current permissions, set them to perm 0755, stop the currently running jenkins anchore container, and restart the system against the volume with new permissions.

1) ls -lad /path/to/your/local_anchore_data_volume/
2) chmod 0755 /path/to/your/local_anchore_data_volume/
3) docker stop jenkins_anchore
4) retry the jenkins job

If this doesn't track with your local setup, let us know more about your settings and perhaps some output of your data volume permissions and we can go from there!

Best
-Dan

**Comment by milindbangar79** [comment]
Hi Nurmi, 

Apologies for late reply. Plugin is working fine now.

Regards
Milind
